/cgps/nv/item_files/
/cgps/nv/item_files/me/gnss_dynamic_pga_config
/cgps/nv/item_files/me/gnss_sp_on_heap_alloc_fail_buf_num
/cgps/nv/item_files/me/gnss_sp_on_heap_alloc_fail_test_id
/cgps/nv/item_files/me/gnss_sp_on_heap_alloc_mode
/cgps/nv/item_files/me/gnss_me_rfgd_bds2glo_uncertainty_ns
/nv/item_files/gps/cgps/me/gnss_me_rfgd_bds2glo_ns
/cgps/nv/item_files/me/gnss_me_rfgd_bds_uncertainty_ns
/nv/item_files/gps/cgps/me/gnss_me_rfgd_bds_ns
/nv/item_files/gps/cgps/me/gnss_apq_pga_cal
/nv/item_files/gps/cgps/me/gnss_bds_path_loss
/nv/item_files/gps/cgps/me/gnss_config
/cgps/nv/item_files/me/gnss_span_timers
/cgps/nv/item_files/me/gnss_span_control
/nv/item_files/gps/cgps/me/gnss_lte_b13_tx_gps_xcorr_mask_increase
/nv/item_files/gps/cgps/me/gnss_peak_antenna_gain
/cgps/nv/item_files/me/gnss_me_gps_5ms_iqsum_logging
/nv/item_files/gps/cgps/me/gnss_wlan_bt_delta_tx_antenna_im_jamming_power
/nv/item_files/gps/cgps/me/gnss_aux_wwan_tx_antenna_im_jamming_power
/nv/item_files/gps/cgps/me/gnss_main_wwan_tx_antenna_im_jamming_power
/cgps/nv/item_files/me/gnss_me_valid_taugps_unc_bound_ns
/cgps/nv/item_files/me/gnss_me_rfgd_glo_uncertainty_ns
/nv/item_files/gps/cgps/me/gnss_me_rfgd_glo_ns
/nv/item_files/gps/cgps/me/gnss_me_celldb_max_timetag_age_sec
/nv/item_files/gps/cgps/me/gnss_pp_disable_lte_detection_increase
/cgps/nv/item_files/me/gnss_added_frequency_offset
/cgps/nv/item_files/me/gnss_gsm_blanking_control
/cgps/nv/item_files/me/gnss_notch_filter_control
/cgps/nv/item_files/me/gnss_clock_source
/cgps/nv/item_files/me/gnss_external_lna_state
/cgps/nv/item_files/me/gnss_nv_access_control
