/cgps/nv/item_files/ulp/tle/gnss_tle_test_control
/cgps/nv/item_files/ulp/tle/gnss_tle_write_to_storage_control
/cgps/nv/item_files/ulp/tle/gnss_tle_selflearned_db_max_pages
/cgps/nv/item_files/ulp/tle/gnss_tle_region_db_max_pages
/cgps/nv/item_files/ulp/tle/gnss_tle_cell_db_max_pages
/cgps/nv/item_files/ulp/tle/gnss_xtrat_keep_warm_timeout
/cgps/nv/item_files/ulp/tle/gnss_xtrat_time_inject_tunc
/cgps/nv/item_files/ulp/tle/gnss_xtrat_time_injection_control
/cgps/nv/item_files/ulp/tle/gnss_tle_cellid_l4_dft_radius
/cgps/nv/item_files/ulp/tle/gnss_tle_cellid_l3_dft_radius
/cgps/nv/item_files/ulp/tle/gnss_tle_cellid_l2_dft_radius
/cgps/nv/item_files/ulp/tle/gnss_tle_database_age_threshold_unit
/cgps/nv/item_files/ulp/tle/gnss_tle_database_age_threshold
