/nv/item_files/gps/cgps/sm/gm_motion_state_speed_config
/nv/item_files/gps/cgps/sm/gm_challenging_gps_env_motion_sensing_dist_config
/nv/item_files/gps/cgps/sm/gm_challenging_gps_env_backoff_config
/nv/item_files/gps/cgps/sm/gm_med_resp_backoff
/nv/item_files/gps/cgps/sm/gm_cpi_request_rate
/nv/item_files/gps/cgps/sm/gnss_nv_efs_sm_e911_config
/nv/item_files/gps/cgps/sm/gm_high_responsiveness_config
/nv/item_files/gps/cgps/sm/gm_use_nw_asst_fixes
/nv/item_files/gps/cgps/sm/gm_gnss_max_pos_unc_accepted
/nv/item_files/gps/cgps/sm/wifi_wait_timeout_sec
/nv/item_files/gps/cgps/xtra/gnss_xtra3_last_key_index
/nv/item_files/gps/cgps/sm/gm_position_sources
/nv/item_files/gps/cgps/sm/gm_gnss_position_qos_session_timeout
/nv/item_files/gps/cgps/sm/gm_motion_detection_sources
/nv/item_files/gps/cgps/sm/gm_gnss_unavail_ind_timeout
/nv/item_files/gps/cgps/sm/gnss_lm_hepe_threshold
/nv/item_files/gps/cgps/sm/gnss_emergency_session_protocol_select
/nv/item_files/gps/cgps/sm/gnss_lpp_cp_timeout
/nv/item_files/gps/cgps/sm/gnss_config_premium_service
/nv/item_files/gps/cgps/sm/gnss_assisted_glo_protocol_select
/nv/item_files/gps/cgps/qmi/gnss_qmi_config
/nv/item_files/gps/cgps/sm/gnss_agps_rat_pref_config
/nv/item_files/gps/cgps/sm/gnss_lpp_enable
/nv/item_files/gps/cgps/sm/gnss_1x_up_supl_enable
/nv/item_files/gps/cgps/sm/gnss_send_no_fix_report
/nv/item_files/gps/cgps/xtra/cgps_xtra_preferred_max_valid_age
