/nv/item_files/ims/IMS_enable
/nv/item_files/ims/ims_rtp_loop_back_enabled
/nv/item_files/ims/qp_ims_reg_config
/nv/item_files/ims/qp_ims_vs_config
/nv/item_files/ims/qp_ims_voip_config
/nv/item_files/ims/qp_ims_sip_extended_0_config
/nv/item_files/ims/qp_ims_rcs_config
/nv/item_files/ims/qp_ims_dpl_config
/nv/item_files/ims/qp_ims_param_config
/nv/item_files/ims/qp_ims_sms_config
/nv/item_files/ims/qp_ims_presence_config
/nv/item_files/ims/qp_ims_media_config
/nv/item_files/ims/qipcall_config_items
/nv/item_files/ims/qipcall_codec_mode_set_amr_wb
/nv/item_files/ims/qipcall_octet_aligned_mode_amr_wb
/nv/item_files/ims/qipcall_octet_aligned_mode_amr_nb
/nv/item_files/ims/voip_prfrd_codec
/nv/item_files/ims/qipcall_session_level_media_bw_enabled
/nv/item_files/ims/qipcall_qos_enabled
/nv/item_files/ims/qipcall_confrd_uri
/nv/item_files/ims/qipcall_dan_enable
/nv/item_files/ims/qipcall_callerid_mode
/nv/item_files/ims/qipcall_refer_subscription_expires_duration
/nv/item_files/ims/qipcall_notify_refer_response_duration
/nv/item_files/ims/qipcall_precondition_enable
/nv/item_files/ims/qipcall_qos_reservation_timer
/nv/item_files/ims/qipcall_vt_quality_selector
/nv/item_files/ims/qipcall_enable_hd_voice
/nv/item_files/ims/qipcall_codec_mode_set
/nv/item_files/ims/qipcall_domain_selection_enable
/nv/item_files/ims/qipcall_is_conf_server_refer_recipient
/nv/item_files/ims/qipcall_rtcp_link_aliveness_timer
/nv/item_files/ims/qipcall_rtcp_reporting_interval
/nv/item_files/ims/qipcall_dan_hysterisis_timer_duration
/nv/item_files/ims/qipcall_dan_needed
/nv/item_files/ims/qipcall_1xsmsandvoice
/nv/item_files/ims/qipcall_ringback_timer
/nv/item_files/ims/qipcall_ringing_timer
/nv/item_files/ims/qipcall_rtp_link_aliveness_timer
/nv/item_files/ims/ims_scr_amr_wb_enabled
/nv/item_files/ims/ims_scr_amr_nb_enabled
/nv/item_files/ims/ims_operation_mode
/nv/item_files/ims/ims_user_agent
/nv/item_files/ims/qp_ims_config
/nv/item_files/ims/qipcall_dan_retry_timer_duration
/nv/item_files/ims/qipcall_dan_max_retry_count
/nv/item_files/ims/qipcall_dan_channel_preference
/nv/item_files/ims/qipcall_signal_strength_threshold
/nv/item_files/ims/qipcall_is_conference_aware
/nv/item_files/ims/qp_ims_reg_extended_0_config
/nv/item_files/ims/qp_ims_ut_config
/nv/item_files/ims/qp_ims_rcs_auto_config
/nv/item_files/ims/qp_ims_rcs_imscore_auto_config
/nv/item_files/ims/ims_hybrid_enable
/nv/item_files/ims/qp_ims_vt_4G_media_capability
/nv/item_files/ims/qp_ims_vs_4G_media_capability
/nv/item_files/ims/qp_ims_vt_3G_media_capability
/nv/item_files/ims/qp_ims_vs_3G_media_capability
/nv/item_files/ims/qp_ims_vs_WLAN_media_capability
/nv/item_files/ims/qp_ims_vt_WLAN_media_capability
/nv/item_files/ims/qp_ims_ussd_config
/nv/item_files/ims/qp_ims_presence_ext_config
/nv/item_files/ims/qp_ims_qos_config
/nv/item_files/ims/qp_ims_reg_config_db
/nv/item_files/ims/qp_ims_test_mode
/nv/item_files/ims/qp_ims_cellid
/nv/item_files/ims/qp_ims_wifi_config
/nv/item_files/ims/qipcall_invite_retry_counter
