/nv/item_files/mcfg/mcfg_autoselect_by_uim
/nv/item_files/mcfg/mcfg_config_force_load
/nv/item_files/mcfg/mcfg_def_config_enable
/nv/item_files/mcfg/mcfg_def_config_force_load
/nv/item_files/mcfg/mcfg_segload_config
