/nv/item_files/wcdma/rrc/wcdma_rrc_wtol_cm_support
/nv/item_files/wcdma/rrc/wcdma_ppac_support
/nv/item_files/wcdma/rrc/wcdma_rrc_save_acqdb
/nv/item_files/wcdma/rrc/wcdma_rrc_band_priority_config
/nv/item_files/wcdma/rrc/wcdma_rrc_disable_cpc_fdpch
/nv/item_files/wcdma/rrc/wcdma_rrc_disable_crash_debug_info
/nv/item_files/wcdma/rrc/wcdma_rrc_wtol_ps_ho_support
/nv/item_files/wcdma/rrc/wcdma_rrc_wtol_tdd_ps_ho_support
/nv/item_files/wcdma/rrc/wcdma_rrc_enable_psc_lock
/nv/item_files/wcdma/rrc/wcdma_rrc_csg_prune_counter
/nv/item_files/wcdma/rrc/wcdma_csg_srch_carrier_space
/nv/item_files/wcdma/rrc/wcdma_asf_timer
/nv/item_files/wcdma/rrc/wcdma_rrc_ignore_cell_bar_reserve_status
/nv/item_files/wcdma/rrc/wcdma_rrc_snow3g_enabled
/nv/item_files/wcdma/rrc/wcdma_rrc_set_srb2_act_time
/nv/item_files/wcdma/rrc/wcdma_rrc_csfb_skip_sib11_opt
/nv/item_files/wcdma/rrc/wcdma_rrc_freq_lock_item
/nv/item_files/wcdma/rrc/wcdma_rrc_do_not_forward_page
/nv/item_files/wcdma/rrc/wcdma_rrc_fast_return_to_lte_after_csfb
/nv/item_files/wcdma/rrc/wcdma_rrc_fast_return_to_lte_after_csfb_timer
/nv/item_files/wcdma/rrc/wcdma_rrc_freq_scan_timer_in_ms
/nv/item_files/wcdma/rrc/wcdma_rrc_deep_sleep_no_svc_timer_in_ms
/nv/item_files/wcdma/rrc/wcdma_rrc_bplmn_freq_scan_timer_in_ms
/nv/item_files/wcdma/rrc/rrc_ganss_support_nv
/nv/item_files/wcdma/rrc/wcdma_rrc_sib_sleep_sb
/nv/item_files/wcdma/rrc/rrc_fe_fach_support
/nv/item_files/wcdma/rrc/rrc_dsds_concurrency_extended
/nv/item_files/wcdma/rrc/rrc_dsda_concurrency_extended
/nv/item_files/wcdma/rrc/rrc_nv_enable_mfbi_support
/nv/item_files/wcdma/rrc/rrc_constant_320ms_drx
/nv/item_files/wcdma/rrc/rrc_ul_compr_cap_support
/nv/item_files/wcdma/rrc/rrc_dsds_concurrency
