/nv/item_files/modem/lte/ML1/update_band_range
/nv/item_files/modem/lte/common/lte_category
/nv/item_files/modem/lte/ML1/bs_bw_supported
/nv/item_files/modem/lte/common/ca_disable
/nv/item_files/modem/lte/rrc/cap/fgi
/nv/item_files/modem/lte/rrc/cap/fgi_rel9
/nv/item_files/modem/lte/rrc/cap/fgi_tdd
/nv/item_files/modem/lte/rrc/cap/fgi_tdd_rel9
/nv/item_files/modem/lte/rrc/cap/dual_rx_1x_csfb
/nv/item_files/modem/lte/rrc/cap/diable_e_csfb_1xrtt
/nv/item_files/modem/lte/rrc/cap/diff_fdd_tdd_fgi_enable
/nv/item_files/modem/lte/rrc/cap/disable_r9_redirection
/nv/item_files/modem/lte/rrc/cap/fgi_r10
/nv/item_files/modem/lte/rrc/cap/fgi_tdd_rel10
/nv/item_files/modem/lte/rrc/cap/disable_ca_bandwidth_combo
/nv/item_files/modem/lte/rrc/cap/disable_ca_intra_band_validation
/nv/item_files/modem/lte/rrc/cap/mdt_r10_feature_disable
/nv/item_files/modem/lte/rrc/cap/fgi
/nv/item_files/modem/lte/rrc/cap/fgi_rel9
/nv/item_files/modem/lte/rrc/cep/try_count
/nv/item_files/modem/lte/rrc/cep/oos_after_2_t300_expiry
/nv/item_files/modem/lte_connection_control
/nv/item_files/modem/lte/rrc/cep/conn_control_param_cfg
/nv/item_files/modem/lte/rrc/cep/conn_control_barring_optmz_enable
/nv/item_files/modem/lte/rrc/cep/r12_ssac_in_conn
/nv/item_files/modem/lte/rrc/sec/eia0_allowed
/nv/item_files/modem/lte/rrc/config/reconfig_wait_time
/nv/item_files/modem/lte/rrc/config/nas_pdu_in_recfg_validation
/nv/item_files/modem/lte/rrc/csg/csg_control
/nv/item_files/modem/lte/rrc/csp/lte_redir_test
/nv/item_files/modem/lte/rrc/csp/pci_lock
/nv/item_files/modem/lte/rrc/csp/earfcn_lock
/nv/item_files/modem/lte/rrc/csp/band_priority_list
/nv/item_files/modem/lte/rrc/csp/lte_rrc_save_acqdb
/nv/item_files/modem/lte/rrc/csp/cell_barring
/nv/item_files/modem/lte/rrc/csp/lfs_disabled
/nv/item_files/modem/lte/rrc/csp/short_cell_barring_time
/nv/item_files/modem/lte/rrc/csp/reduced_barring_time
/nv/item_files/modem/lte/rrc/csp/backoff_barring_time
/nv/item_files/modem/lte/rrc/csp/rlf_system_scan_duration
/nv/item_files/modem/lte/rrc/emp/mcch
/nv/item_files/modem/lte/rrc/emp/mcch_time
/nv/item_files/modem/lte/embms_oos_time
/nv/item_files/modem/lte/rrc/embms_over_unicast
/nv/item_files/modem/lte/rrc/embms_feature_status
/nv/item_files/modem/lte/embms_priority_cfg
/nv/item_files/modem/lte/rrc/irat/gsm
/nv/item_files/modem/lte/rrc/irat/tdscdma_blind
/nv/item_files/modem/lte/rrc/irat/wcdma_blind
/nv/item_files/modem/lte/rrc/lte_rrc_1xcsfb_enabled
/nv/item_files/modem/lte/rrc/mdt/t330
/nv/item_files/modem/lte/rrc/mdt/report_log_avai
/nv/item_files/modem/lte/rrc/mdt/valid_tmr
/nv/item_files/modem/lte/rrc/mdt/max_heap_mem
/nv/item_files/modem/lte/rrc/dup_meas_obj_chk_enabled
/nv/item_files/modem/lte/rrc/qty_chk_enabled
/nv/item_files/modem/lte/rrc/skip_conn_meas_rat_validation
/nv/item_files/modem/lte/rrc/sib/etws
/nv/item_files/modem/lte/rrc/sib/cmas
/nv/item_files/modem/lte/rrc/bplmn/bplmn_control
/nv/item_files/modem/lte/rrc/sec/eia0_allowed
/nv/item_files/modem/lte/rrc/sib/sib1
/nv/item_files/modem/lte/rrc/sib/sib2
/nv/item_files/modem/lte/rrc/sib/sib13
/nv/item_files/modem/lte/rrc/sib/mand_sibs_tmr
/nv/item_files/modem/lte/rrc/sib/non_mand_sibs_tmr
/nv/item_files/modem/lte/rrc/sib/sib16_utc_sibs_tmr
/nv/item_files/modem/lte/rrc/sib/etws
/nv/item_files/modem/lte/rrc/sib/cmas
/nv/item_files/modem/lte/rrc/b12_to_b17
/nv/item_files/modem/lte/rrc/ueinfo/valtmr
/nv/item_files/modem/lte/rrc/lte_rrc_release_ver
/nv/item_files/modem/lte/lte_3gpp_release_ver
/nv/item_files/modem/lte/rrc/lte_tdd_prune
/nv/item_files/modem/lte/axgp
/nv/item_files/modem/lte/rrc/rohc_supported
/nv/item_files/modem/lte/rrc/lte_deprio_supported
/nv/item_files/modem/lte/rrc/lte_rrc_asn1_profiling_enabled