/nv/item_files/modem/uim/mmgsdi/refresh_retry
/nv/item_files/modem/uim/mmgsdi/mmgsdi_diag_support
/nv/item_files/modem/uim/mmgsdi/halt_subscription
/nv/item_files/modem/uim/mmgsdi/encrypt_sub_ok
/nv/item_files/modem/uim/mmgsdi/refresh_vote_ok
/nv/item_files/modem/uim/mmgsdi/csim_device_model
/nv/item_files/modem/uim/mmgsdi/features_status_list
/nv/item_files/modem/uim/mmgsdi/auto_activate_onchip
/mmgsdi/onchip/onchip_slot1
/nv/item_files/modem/uim/mmgsdi/ens_sub_features_status_list
/nv/item_files/modem/uim/gstk/feature_bmsk
/nv/item_files/modem/uim/gstk/tp_clients
/nv/item_files/modem/uim/gstk/attach_ctrl_timer
/nv/item_files/modem/uim/gstk/redial_cfg
/nv/item_files/modem/uim/gstk/proactive_feature_enable_cfg
/nv/item_files/modem/uim/gstk/cat_version
/nv/item_files/modem/qmi/cat/qmi_cat_mode
/nv/item_files/modem/uim/gstk/bip_otasp_concurrency
/nv/item_files/modem/uim/gstk/tal_conf
/nv/item_files/modem/uim/gstk/me_feature_bmsk
/nv/item_files/modem/qmi/cat/qmi_cat_mode
/nv/item_files/modem/qmi/cat/qmi_cat_vs_id
/nv/item_files/modem/qmi/cat/qmi_cat_custom_tp
/nv/item_files/modem/qmi/cat/qmi_cat_default_lang
/nv/item_files/modem/qmi/cat/qmi_cat_display_alpha
/nv/item_files/modem/qmi/cat/qmi_cat_block_sms_pp_env
/nv/item_files/modem/qmi/uim/sap_security_restrictions
/nv/item_files/modem/qmi/uim/auth_security_restrictions
/nv/item_files/modem/qmi/uim/apdu_security_restrictions
/nv/item_files/modem/qmi/uim/qmi_uim_silent_pin1
/nv/item_files/modem/qmi/uim/apdu_security_aid_list
/nv/item_files/modem/qmi/uim/close_channel_sync
/nv/item_files/modem/qmi/uim/silent_recovery
