/nv/item_files/modem/mmode/sms_only
/nv/item_files/modem/mmode/ue_usage_setting
/nv/item_files/modem/mmode/voice_domain_pref
/nv/item_files/modem/mmode/sms_domain_pref
/nv/item_files/modem/mmode/lte_disable_duration
/nv/item_files/modem/mmode/n_min_MO_call_soft_retry
/nv/item_files/modem/mmode/n_maxSIB8
/nv/item_files/modem/mmode/sms_mandatory
/nv/item_files/modem/mmode/lte_bandpref
/nv/item_files/modem/mmode/tds_bandpref
/nv/item_files/modem/mmode/device_mode
/nv/item_files/mcs/mtf/cp_mutex_tracking_enabled
/nv/item_files/modem/mmode/sd/loc_base_bsr_mcc_list
/nv/item_files/modem/mmode/supplement_service_domain_pref
/nv/item_files/modem/mmode/sms_over_s102
/nv/item_files/modem/mmode/operator_name
/nv/item_files/modem/mmode/qmss_enabled
/nv/item_files/modem/mmode/sd/1xcsfb_ecbm_status
/nv/item_files/modem/mmode/get_net_auto_mode
/nv/item_files/modem/mmode/global_mode_csg
/nv/item_files/modem/mmode/custom_emerg_info
/nv/item_files/modem/mmode/manufacturer_name
/nv/item_files/modem/mmode/manufacturer_code
/nv/item_files/modem/mmode/device_model
/nv/item_files/modem/mmode/sw_version
/nv/item_files/modem/mmode/cu_imsi
/nv/item_files/modem/mmode/cmcc_imsi
/nv/item_files/modem/mmode/imsi_mcc
/nv/item_files/modem/mmode/imsi_min1
/nv/item_files/modem/mmode/imsi_min2
/nv/item_files/modem/mmode/imsi_11_12
/nv/item_files/modem/mmode/reg_status
/nv/item_files/modem/mmode/mid_call_srvcc_info
/nv/item_files/modem/mmode/lte_do_irat_duration
/nv/item_files/modem/mmode/volte_sr_control
/nv/item_files/modem/mmode/extend_lte_disable_duration
/nv/item_files/modem/mmode/sd/manual_search_in_wrlf
/nv/item_files/modem/mmode/supportfordualrxues
/nv/item_files/modem/mmode/sxlte_timers
/nv/item_files/modem/mmode/msim_standby_esr_support
/nv/item_files/modem/mmode/3gpp2_ps_call_optimization
/nv/item_files/modem/mmode/sms_domain_pref_list
/nv/item_files/modem/mmode/allow_csfb_upon_ims_reg
/nv/item_files/modem/mmode/sd/c2k_resel_splmn_supp
/nv/item_files/modem/mmode/sd/buffer_int_srv_lost
/nv/item_files/modem/mmode/sd/1xcsfb_call_end_opt
/nv/item_files/modem/mmode/ssac_hvolte
/nv/item_files/modem/mmode/mode_disabled_in_TSTS
/nv/item_files/modem/mmode/1xsrvcc_stn_sr_number
/nv/item_files/modem/mmode/sd/full_srv_req_in_emerg
/nv/item_files/modem/mmode/scan_scope_rule
/nv/item_files/modem/mmode/allow_sms_in_ecbm
/nv/item_files/modem/mmode/ue_based_cw
/nv/item_files/modem/mmode/wifi_config
/nv/item_files/modem/mmode/c2k_switch_2_srlte
