/nv/item_files/modem/nas/geran_cap
/nv/item_files/modem/nas/lte_nas_lsti_config
/nv/item_files/modem/nas/lte_nas_ue_sec_capability
/nv/item_files/modem/nas/lte_nas_temp_fplmn_backoff_time
/nv/item_files/modem/nas/lte_nas_srlte_esr_time
/nv/item_files/modem/nas/drx_cn_coeff_s1
/nv/item_files/modem/nas/exclude_ptmsi_type_field
/nv/item_files/modem/nas/exclude_old_lai_type_field
/nv/item_files/modem/nas/nas_lai_change_force_lau_for_emergency
/nv/item_files/modem/nas/nas_srvcc_support
/nv/item_files/modem/nas/l21xsrvcc_support
/nv/item_files/modem/nas/mobility_management_for_voims_feature
/nv/item_files/modem/nas/nas_config_feature
/nv/item_files/modem/nas/aggression_management
/nv/item_files/modem/nas/csg_support_configuration
/nv/item_files/modem/nas/nas_l2g_srvcc_support
/nv/item_files/modem/nas/tighter_capability
/nv/item_files/modem/nas/nas_nv_classmark_ie
/nv/item_files/modem/nas/sglte_nas_nv_config
/nv/item_files/modem/nas/mm_backoff_remaining_info
/nv/item_files/modem/nas/mm_backoff_remaining_info_subscription01
/nv/item_files/modem/nas/gmm_drx_cn_coeff_s1
/nv/item_files/modem/nas/isr
/nv/item_files/modem/nas/emm_combined_proc
/nv/item_files/modem/nas/conn_mode_manual_search
/nv/item_files/modem/nas/avoid_guti_nas_security_check
/nv/item_files/modem/nas/is_accepted_on_lte
/nv/item_files/modem/nas/lte_nas_ignore_mt_csfb_during_volte_call
/nv/item_files/modem/nas/mm_manual_search_timer_value
/nv/item_files/modem/nas/early_call_init
