/nv/item_files/modem/1x/zz2_2_thresh
/nv/item_files/modem/1x/zz2_2_sel_parms
/nv/item_files/modem/1x/rin_thresh
/nv/item_files/modem/1x/new_rdds_params
/nv/item_files/modem/1x/div_asd_int_thresh
/nv/item_files/modem/1x/div_asd
/nv/item_files/modem/1x/acq_pri_timers
