/nv/item_files/datacommon/utils/aka_auth_info
/nv/item_files/datacommon/utils/aka_in_sw
/nv/item_files/datacommon/utils/is_fmc_enabled
/nv/item_files/datacommon/utils/is_at_kdf_in_aka_prime_sync_fail_enabled
/nv/item_files/datamodem/protocols/ip6_default_mtu
/nv/item_files/datamodem/protocols/ip6_include_rdnss_opt
/nv/item_files/data/protocols/icmp_reply_rate
/nv/item_files/datamodem/protocols/ipv6_ext_addr_probe_config_items
/nv/item_files/datamodem/protocols/icmp6_mdm_iid_fltr_enable
