/nv/item_files/jcdma/uim_jcdma_mode
/nv/item_files/modem/uim/uimdrv/me_hotswap_configuration
/nv/item_files/modem/uim/uimdrv/uim_features_status_list
/nv/item_files/modem/uim/uimdrv/uim_hw_config
/nv/item_files/modem/uim/uimdrv/feature_support_hotswap
/nv/item_files/modem/uim/uimdrv/nv_active_slot_configuration
/nv/item_files/modem/uim/uimdrv/nv_pdown_uim_consecutive_techproblems
/nv/item_files/modem/uim/uimdrv/sim_response_timers_config
/nv/item_files/modem/uim/uimdrv/uim_busy_response_simulate_null_config
