#!/bin/sh

LED="/sys/class/leds/blue:wan"
[ -d "$LED" ] || LED="/sys/class/leds/blue:wlan"

[ -d "$LED" ] || exit 0

blue_off()
{
        echo none > "$LED/trigger" 2>/dev/null
        echo 0 > "$LED/brightness" 2>/dev/null
}

blue_blink()
{
        echo timer > "$LED/trigger" 2>/dev/null
        echo 500 > "$LED/delay_on" 2>/dev/null
        echo 500 > "$LED/delay_off" 2>/dev/null
}

case "$ACTION:$INTERFACE" in

        ifup:modem)
                blue_blink
                logger -t modem-blue-led \
                        "LTE interface up: blue BLINK"
                ;;

        ifdown:modem)
                blue_off
                logger -t modem-blue-led \
                        "LTE interface down: blue OFF"
                ;;

esac

exit 0
