#!/bin/sh
# Enable the A2-hold service on HMU05 boards.
# The modem asserts `a2_power.c:1189` on the A2 power-down/up cycle once a data
# bearer is up; pinning bam-dmux power/control=on freezes the A2 and prevents it.
# See /usr/sbin/modem-a2-hold.

. /lib/functions.sh 2>/dev/null

case "$(board_name 2>/dev/null)" in
	*hmu05*)
		[ -x /etc/init.d/modem-a2-hold ] && /etc/init.d/modem-a2-hold enable
		;;
esac

exit 0
