services:
  builder:
    build:
      context: ..
      dockerfile: devenv/Dockerfile
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}

    container_name: openwrt-builder

    working_dir: /repo/openwrt

    stdin_open: true
    tty: true

    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"

    volumes:
      - ..:/repo

    command: ["/bin/bash"]
